All: vc707
# . /home/apps/xilinx/Vivado_2013.03/Vivado/2013.3/settings64.sh
vc707:
	vivado -mode tcl -source nn_core_vc707_batch.tcl
gui:
	vivado -source create_project_nn_core_vc707_vivado_2013.03.tcl
clean:
	rm -f *.log *.jou
