#
# Vivado (TM) v2013.3 (64-bit)
#
# create_project_nn_core_vc707_vivado_2013.03.tcl: Tcl script for re-creating project 'nn_core_vc707'
#
# Generated by Vivado on Wed Dec 06 15:55:35 +07 2017
# IP Build 192953 on Wed Oct 16 08:44:02 MDT 2013
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_project_nn_core_vc707_vivado_2013.03.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/NN_CORE.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/b2_1.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/b2_2.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/b2_3.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/b3_1.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/b3_2.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/backward.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/counter.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/dadz.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/db_adder.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/delay1.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/delta2.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/delta3.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/dw.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/dw_adder.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/forward.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/gen_din_sel.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/k1.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/k2.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/mem.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/sel_k.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/selector.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/t1.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/t2.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/w2_11.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/w2_12.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/w2_13.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/w2_21.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/w2_22.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/w2_23.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/w3_11.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/w3_12.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/w3_21.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/w3_22.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/w3_31.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/w3_32.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/z2.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/rtl/z3.v"
#    "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/fpga/nn_core_vc707/nn_core_vc707.srcs/constrs_1/new/nn_core.xdc"
#
#*****************************************************************************************

# Set the original project directory path for adding/importing sources in the new project
set orig_proj_dir "/home/nobawk/work/sislab/lsi_contest_2018/src/verilog/fpga/nn_core_vc707"

# Create project
create_project nn_core_vc707 ./nn_core_vc707

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects nn_core_vc707]
set_property "board" "xilinx.com:virtex7:vc707:1.1" $obj
set_property "simulator_language" "Mixed" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Add files to 'sources_1' fileset
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "../rtl/NN_CORE.v"]"\
 "[file normalize "../rtl/b2_1.v"]"\
 "[file normalize "../rtl/b2_2.v"]"\
 "[file normalize "../rtl/b2_3.v"]"\
 "[file normalize "../rtl/b3_1.v"]"\
 "[file normalize "../rtl/b3_2.v"]"\
 "[file normalize "../rtl/backward.v"]"\
 "[file normalize "../rtl/counter.v"]"\
 "[file normalize "../rtl/dadz.v"]"\
 "[file normalize "../rtl/db_adder.v"]"\
 "[file normalize "../rtl/delay1.v"]"\
 "[file normalize "../rtl/delta2.v"]"\
 "[file normalize "../rtl/delta3.v"]"\
 "[file normalize "../rtl/dw.v"]"\
 "[file normalize "../rtl/dw_adder.v"]"\
 "[file normalize "../rtl/forward.v"]"\
 "[file normalize "../rtl/gen_din_sel.v"]"\
 "[file normalize "../rtl/k1.v"]"\
 "[file normalize "../rtl/k2.v"]"\
 "[file normalize "../rtl/mem.v"]"\
 "[file normalize "../rtl/sel_k.v"]"\
 "[file normalize "../rtl/selector.v"]"\
 "[file normalize "../rtl/t1.v"]"\
 "[file normalize "../rtl/t2.v"]"\
 "[file normalize "../rtl/w2_11.v"]"\
 "[file normalize "../rtl/w2_12.v"]"\
 "[file normalize "../rtl/w2_13.v"]"\
 "[file normalize "../rtl/w2_21.v"]"\
 "[file normalize "../rtl/w2_22.v"]"\
 "[file normalize "../rtl/w2_23.v"]"\
 "[file normalize "../rtl/w3_11.v"]"\
 "[file normalize "../rtl/w3_12.v"]"\
 "[file normalize "../rtl/w3_21.v"]"\
 "[file normalize "../rtl/w3_22.v"]"\
 "[file normalize "../rtl/w3_31.v"]"\
 "[file normalize "../rtl/w3_32.v"]"\
 "[file normalize "../rtl/z2.v"]"\
 "[file normalize "../rtl/z3.v"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "NN_CORE" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Add files to 'constrs_1' fileset
set obj [get_filesets constrs_1]
set files [list \
 "[file normalize "./nn_core_vc707.xdc"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'constrs_1' fileset file properties for remote files
set file "./nn_core_vc707.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects constrs_1 [list "*$file"]]
set_property "file_type" "XDC" $file_obj


# Set 'constrs_1' fileset file properties for local files
# None

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets sim_1] ""]} {
  create_fileset -simset sim_1
}

# Add files to 'sim_1' fileset
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "NN_CORE" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs synth_1] ""]} {
  create_run -name synth_1 -part xc7vx485tffg1761-2 -flow {Vivado Synthesis 2013} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
}
set obj [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs impl_1] ""]} {
  create_run -name impl_1 -part xc7vx485tffg1761-2 -flow {Vivado Implementation 2013} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
}
set obj [get_runs impl_1]


puts "INFO: Project created:nn_core_vc707"
